apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: laravel-role
  namespace: default
rules:
  - apiGroups: [""]
    resources: ["pods", "jobs", "cronjobs", "pods/log"]
    verbs: ["get", "list", "watch", "create", "delete"]
